In [1]:
import numpy as np

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[9]

np.int64(20)

In [7]:
arr[1:5]

array([12, 13, 14, 15])

In [8]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [9]:
arr[5]

array([26, 27, 28, 29, 30])

In [10]:
arr[0,0]

np.int64(1)

In [11]:
 arr[0,4]

np.int64(5)

In [12]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [14]:
slice  = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [15]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [19]:
slice = arr[2:3,3:]
slice

array([[14, 15]])

In [20]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [21]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
bool_index  = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [23]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [39]:
import numpy as np #array operations

In [40]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [41]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [42]:
a1 // a2

array([0, 0, 0, 0, 0])

In [43]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [44]:
l = [1,2,3,4]  #broadcasting
arr = np.array(l)

In [45]:
arr +10

array([11, 12, 13, 14])

In [46]:
#matrix operation


A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [47]:
A @B

array([[19, 22],
       [43, 50]])

In [48]:
A.T

array([[1, 3],
       [2, 4]])

In [51]:
# stack arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [52]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [56]:
#splitting array


c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [58]:
np.vsplit(c, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]