In [32]:
import numpy as np

In [33]:
arr = np.array([1,3,6,8])
arr

array([1, 3, 6, 8])

In [34]:
a =[1,2,3.5,"hello"]
a

[1, 2, 3.5, 'hello']

In [35]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [36]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [37]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [38]:
arr  = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [39]:
arr = np.ones((3,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [40]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [41]:
arr = np.arange(1, 10)
print(arr)

[1 2 3 4 5 6 7 8 9]
